id = "symbols"
name = "Symbols"
version = "0.2.3"
schema_version = 1
authors = ["Miguel Solorio <unknown@unknown.dev>"]
description = "A simple file icon theme"
repository = "https://github.com/sebastiandotdev/zed-symbols"
