id = "symbols"
name = "Symbols"
version = "0.0.24"
schema_version = 1
authors = ["Miguel Solorio <unknown@unknown.dev>"]
description = "A simple file icon theme"
repository = "https://github.com/miguelsolorio/vscode-symbols"
